# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
