# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-28 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170619_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, upload_to='product/'),
        ),
    ]
