# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addresslist',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=300),
        ),
    ]
