# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 17:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='+375xxxxxxxxx', max_length=13, validators=[django.core.validators.RegexValidator(regex='^\\+[0-9]{12}$')]),
        ),
    ]
