# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderdate',
        ),
        migrations.AddField(
            model_name='order',
            name='orderenddate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderstartdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='client',
            name='firstname',
            field=models.CharField(default='', help_text='Letters only, max length = 20', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='lastname',
            field=models.CharField(default='', help_text='Letters only, max length = 30', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='80xx-xxx-xx-xx or +375xx-xxx-xx-xx', max_length=13),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(default='', help_text='Only letters, numbers, underscores or hyphens, max length = 20', max_length=20),
        ),
        migrations.AlterField(
            model_name='new',
            name='newsheader',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(default='none', help_text='Use the following format: image002.jpg or gitars/gitara042.png', max_length=255),
        ),
    ]
