# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170615_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.CharField(blank=True, default='', max_length=300, unique=True),
        ),
    ]
