# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 08:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20170614_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(default='none', help_text='Use the following format: image002.jpg or gitars/gitara042.png', max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='+375xxxxxxxxx', max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordercost',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Photo'),
        ),
    ]
