# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170614_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subcategory_id',
            new_name='subcategory',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.AddField(
            model_name='client',
            name='addresslist',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.CharField(default='none', help_text='Use the following format: image002.jpg or gitars/gitara042.png', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CommaSeparatedIntegerField(blank=True, max_length=500),
        ),
    ]
