# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-15 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170615_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='filename',
            field=models.CharField(help_text='Use the following format: image002.jpg or gitars/gitara042.png', max_length=200, unique=True),
        ),
    ]
