# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20170616_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='addresslist',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
